Traceback (most recent call last):
  File "melanoma_classifier.py", line 286, in <module>
    train_df = load_isic_train(args.real_data_path, args.n_imgs)
  File "/ISIC256/project_scripts/GITHUB_REPO/Generative_modelling_for_melanoma_detection/stylegan2-ada-pytorch/utils.py", line 316, in load_isic_train
    list_of_val = pd.read_csv("/ISIC256/real_val.csv/").image_name.tolist()
  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
NotADirectoryError: [Errno 20] Not a directory: '/ISIC256/real_val.csv/'